### ISSUE TITLE
fontello server returns 400

### ISSUE THREAD

**Issue by walkerrandolphsmith** [colophonemes/metalsmith-icons#3]
When I use metalsmith-icons I receive the following error:

```
Unhandled rejection Error: Request to Fontello server returned status code of 400
    at /Users/walkersmith/Repositories/blogr/node_modules/metalsmith-icons/lib/index.js:262:47
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/Users/walkersmith/Repositories/blogr/node_modules/metalsmith-icons/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/walkersmith/Repositories/blogr/node_modules/metalsmith-icons/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/walkersmith/Repositories/blogr/node_modules/metalsmith-icons/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/walkersmith/Repositories/blogr/node_modules/metalsmith-icons/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/walkersmith/Repositories/blogr/node_modules/metalsmith-icons/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/walkersmith/Repositories/blogr/node_modules/metalsmith-icons/node_modules/bluebird/js/release/promise.js:636:18)
    at /Users/walkersmith/Repositories/blogr/node_modules/metalsmith-icons/node_modules/bluebird/js/release/nodeback.js:42:21
    at done (/Users/walkersmith/Repositories/blogr/node_modules/needle/lib/needle.js:382:14)
    at PassThrough.<anonymous> (/Users/walkersmith/Repositories/blogr/node_modules/needle/lib/needle.js:590:9)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

Any ideas on how to resolve this?

**Comment by colophonemes** [comment]
Hey, sorry for the wait, not sure, so I've submitted an issue with the Fontello people:
https://github.com/fontello/fontello/issues/548

**Comment by colophonemes** [comment]
I've stopped getting the error, I suspect it might have been a server issue on their end. Let me know if it comes back.

**Comment by Jazcash** [comment]
I'm getting this error too
